
services:
  ### =========================
  ### Core Services
  ### =========================

  service-aragon-api:
    build:
      context: ./
    container_name: api
    ports:
      - ${SERVICE_API_PORT:-4000}:${SERVICE_API_PORT:-4000}
    environment:
      SERVICES_ARAGON_API_PORT: ${SERVICE_API_PORT:-4000}
      MONGO_DB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/db-aragon?replicaSet=rs0&authSource=admin
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      SERVICES_ARAGON_API_BASE_URL: http://service-aragon-api:4000
    command: yarn service:aragon-api
    depends_on:
      - mongo-init-replica
      - rabbitmq
      

  service-aragon-indexer:
    build:
      context: ./
    container_name: indexer
    environment:
      MONGO_DB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/db-aragon?replicaSet=rs0&authSource=admin
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      SERVICES_ARAGON_API_BASE_URL: http://service-aragon-api:4000
      NODES_HARMONY_MAINNET_FROM_BLOCK: ${NODES_HARMONY_MAINNET_FROM_BLOCK:-82187187}
      NODES_HARMONY_TESTNET_FROM_BLOCK: ${NODES_HARMONY_TESTNET_FROM_BLOCK:-52100000}
    command: yarn service:aragon-indexer
    depends_on:
      - mongo-init-replica
      - rabbitmq
    

  service-aragon-dao:
    build:
      context: ./
    container_name: dao
    environment:
      MONGO_DB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/db-aragon?replicaSet=rs0&authSource=admin
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      SERVICES_ARAGON_API_BASE_URL: http://service-aragon-api:4000
    depends_on:
      - mongo-init-replica
      - rabbitmq
    command: yarn service:aragon-dao
      

  service-aragon-transfers:
    build:
      context: ./
    container_name: transfers    
    environment:
      MONGO_DB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/db-aragon?replicaSet=rs0&authSource=admin
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      SERVICES_ARAGON_API_BASE_URL: http://service-aragon-api:4000
    depends_on:
      - mongo-init-replica
      - rabbitmq
    command: yarn service:aragon-transfers
      

  service-aragon-gateway:
    build:
      context: ./
    container_name: gateway
    environment:
      MONGO_DB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/db-aragon?replicaSet=rs0&authSource=admin
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      SERVICES_ARAGON_API_BASE_URL: http://service-aragon-gateway:4000
    depends_on:
      - mongo-init-replica
      - rabbitmq
    command: yarn service:aragon-gateway
      

  service-aragon-rates:
    build:
      context: ./
    container_name: rates
    environment:
      MONGO_DB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/db-aragon?replicaSet=rs0&authSource=admin
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      SERVICES_ARAGON_API_BASE_URL: http://service-aragon-api:4000
    depends_on:
      - mongo-init-replica
      - rabbitmq
    command: yarn service:aragon-rates
      

  service-aragon-admin-api:
    build:
      context: ./
    ports:
      - ${SERVICE_ADMIN_API_PORT:-4001}:${SERVICE_ADMIN_API_PORT:-4001}
    
    container_name: admin-api
    environment:
      SERVICES_ARAGON_ADMIN_API_PORT: ${SERVICE_ADMIN_API_PORT:-4001}
      MONGO_DB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/db-aragon?replicaSet=rs0&authSource=admin
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      SERVICES_ARAGON_API_BASE_URL: http://service-aragon-api:4000
    depends_on:
      - mongo-init-replica
      - rabbitmq
    command: yarn service:aragon-admin-api
      

  service-aragon-plugins:
    build:
      context: ./
    container_name: plugins
    environment:
      MONGO_DB_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/db-aragon?replicaSet=rs0&authSource=admin
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      SERVICES_ARAGON_API_BASE_URL: http://service-aragon-api:4000
    depends_on:
      - mongo-init-replica
      - rabbitmq
    command: yarn service:aragon-plugins

  ### =========================
  ### Dependencies
  ### =========================

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  mongo1:
    image: mongo:8.0
    container_name: mongo1
    hostname: mongo1
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:8.0
    container_name: mongo2
    hostname: mongo2
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:8.0
    container_name: mongo3
    hostname: mongo3
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db

  mongo-init-replica:
    image: mongo:8.0
    container_name: mongo-init-replica
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: /bin/bash
    command: >
      -c "
      echo 'Waiting a few seconds for MongoDB nodes to be ready...';
      sleep 5;
      echo 'Initializing replica set...';
      mongosh --host mongo1:27017 --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [
            { _id: 0, host: \"mongo1:27017\" },
            { _id: 1, host: \"mongo2:27017\" },
            { _id: 2, host: \"mongo3:27017\" }
          ]
        });
      ';
      echo 'Replica set initialized.'
      "

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
