import type { GovernanceExecutorReason } from '@services/governance-executor/types'
import type { GovernanceProposalRecord } from './types'

const reason = (
  reasonCode: string,
  reasonSeverity: GovernanceExecutorReason['reasonSeverity'],
  source: string,
  message: string,
): GovernanceExecutorReason => ({
  reasonCode,
  reasonSeverity,
  source,
  message,
})

const createdAt = '2026-05-26T00:00:00.000Z'

const governanceProposals: GovernanceProposalRecord[] = [
  {
    proposalId: 'proposal-root-constitutional-review-001',
    governanceProposalRef: 'governance-proposal://tenant-axodus-root/proposal-root-constitutional-review-001',
    daoId: 'axodus-federal-governance',
    tenantId: 'tenant-axodus-root',
    proposalType: 'constitutional-review',
    proposalStatus: 'approved',
    approvalStatus: 'approved',
    executionStatus: 'not_requested',
    executorRef: 'governance-executor://tenant-axodus-root/mock-canonical-executor',
    policyVersion: 'governance-executor-policy-v0.mock',
    constitutionalReference: 'axodus-constitution://v0.mock',
    reasonCodes: [
      reason(
        'MOCK_EXECUTION_MODE_ACTIVE',
        'warning',
        'proposal lifecycle registry',
        'Root DAO proposal is approved but not executable until queued and validated by the canonical executor boundary.',
      ),
    ],
    createdAt,
    submittedAt: createdAt,
    approvedAt: createdAt,
    queuedAt: null,
    executableAt: null,
    executedAt: null,
    cancelledAt: null,
    expiredAt: null,
    blockedAt: null,
  },
  {
    proposalId: 'proposal-tenant-queued-001',
    governanceProposalRef: 'governance-proposal://tenant-executive-dao/proposal-tenant-queued-001',
    daoId: 'dao-executive-001',
    tenantId: 'tenant-executive-dao',
    proposalType: 'local-proposal',
    proposalStatus: 'queued',
    approvalStatus: 'approved',
    executionStatus: 'mock_ready',
    executorRef: 'governance-executor://tenant-executive-dao/mock-tenant-executor',
    policyVersion: 'governance-executor-policy-v0.mock',
    constitutionalReference: 'axodus-constitution://v0.mock',
    reasonCodes: [
      reason(
        'MOCK_EXECUTION_MODE_ACTIVE',
        'warning',
        'proposal lifecycle registry',
        'Queued tenant proposal can only progress to a mock receipt in safe implementation.',
      ),
    ],
    createdAt,
    submittedAt: createdAt,
    approvedAt: createdAt,
    queuedAt: createdAt,
    executableAt: null,
    executedAt: null,
    cancelledAt: null,
    expiredAt: null,
    blockedAt: null,
  },
  {
    proposalId: 'proposal-defi-unsupported-001',
    governanceProposalRef: 'governance-proposal://tenant-executive-dao/proposal-defi-unsupported-001',
    daoId: 'dao-executive-001',
    tenantId: 'tenant-executive-dao',
    proposalType: 'defi-treasury-allocation',
    proposalStatus: 'blocked',
    approvalStatus: 'blocked',
    executionStatus: 'blocked',
    executorRef: 'governance-executor://tenant-executive-dao/mock-tenant-executor',
    policyVersion: 'governance-executor-policy-v0.mock',
    constitutionalReference: 'axodus-constitution://v0.mock',
    reasonCodes: [
      reason(
        'EXECUTOR_PROPOSAL_TYPE_NOT_SUPPORTED',
        'critical',
        'proposal lifecycle registry',
        'DeFi-sensitive proposal type is not supported by the current mock tenant executor policy.',
      ),
    ],
    createdAt,
    submittedAt: createdAt,
    approvedAt: null,
    queuedAt: null,
    executableAt: null,
    executedAt: null,
    cancelledAt: null,
    expiredAt: null,
    blockedAt: createdAt,
  },
  {
    proposalId: 'proposal-mock-executable-001',
    governanceProposalRef: 'governance-proposal://tenant-executive-dao/proposal-mock-executable-001',
    daoId: 'dao-executive-001',
    tenantId: 'tenant-executive-dao',
    proposalType: 'capability-change',
    proposalStatus: 'executable',
    approvalStatus: 'approved',
    executionStatus: 'mock_ready',
    executorRef: 'governance-executor://tenant-executive-dao/mock-tenant-executor',
    policyVersion: 'governance-executor-policy-v0.mock',
    constitutionalReference: 'axodus-constitution://v0.mock',
    reasonCodes: [
      reason(
        'MOCK_EXECUTION_MODE_ACTIVE',
        'warning',
        'proposal lifecycle registry',
        'Proposal is executable only inside the mock receipt boundary.',
      ),
    ],
    createdAt,
    submittedAt: createdAt,
    approvedAt: createdAt,
    queuedAt: createdAt,
    executableAt: createdAt,
    executedAt: null,
    cancelledAt: null,
    expiredAt: null,
    blockedAt: null,
  },
  {
    proposalId: 'proposal-emergency-disabled-001',
    governanceProposalRef: 'governance-proposal://tenant-community-dao/proposal-emergency-disabled-001',
    daoId: 'dao-community-001',
    tenantId: 'tenant-community-dao',
    proposalType: 'legacy-voting-observation',
    proposalStatus: 'emergency_paused',
    approvalStatus: 'blocked',
    executionStatus: 'blocked',
    executorRef: 'governance-executor://tenant-community-dao/legacy-observer',
    policyVersion: 'governance-executor-policy-v0.mock',
    constitutionalReference: 'axodus-constitution://v0.mock',
    reasonCodes: [
      reason(
        'EMERGENCY_EXECUTION_DISABLED',
        'constitutional',
        'proposal lifecycle registry',
        'Executor emergency state prevents proposal execution progression.',
      ),
    ],
    createdAt,
    submittedAt: createdAt,
    approvedAt: null,
    queuedAt: null,
    executableAt: null,
    executedAt: null,
    cancelledAt: null,
    expiredAt: null,
    blockedAt: createdAt,
  },
  {
    proposalId: 'proposal-harmony-observer-001',
    governanceProposalRef: 'governance-proposal://tenant-community-dao/proposal-harmony-observer-001',
    daoId: 'dao-community-001',
    tenantId: 'tenant-community-dao',
    proposalType: 'legacy-voting-observation',
    proposalStatus: 'approved',
    approvalStatus: 'approved',
    executionStatus: 'blocked',
    executorRef: 'governance-executor://tenant-community-dao/legacy-observer',
    policyVersion: 'governance-executor-policy-v0.mock',
    constitutionalReference: 'axodus-constitution://v0.mock',
    reasonCodes: [
      reason(
        'EXECUTION_CHAIN_NOT_AUTHORIZED',
        'constitutional',
        'proposal lifecycle registry',
        'Harmony observer proposal can document votes but cannot become Axodus execution authority.',
      ),
    ],
    createdAt,
    submittedAt: createdAt,
    approvedAt: createdAt,
    queuedAt: null,
    executableAt: null,
    executedAt: null,
    cancelledAt: null,
    expiredAt: null,
    blockedAt: createdAt,
  },
]

export { governanceProposals }
